README.md, main.go, main_lambda_linux_amd64.go, slack_webhook.go, slack_webhook_test.go, util.go, util_test.go
=> Add TRUNCATE_LINES

gitlab_url_parser.go, gitlab_url_parser_test.go, test/gitlab/issue_note.json, test/gitlab/merge_request_note.json
=> Support comment url 

gitlab_page.go, gitlab_url_parser.go, gitlab_url_parser_test.go, slack_webhook.go, test/gitlab/gitlabci-templates/continuous_bundle_update.yml, util.go, util_test.go
=> Support blob URL

gitlab_url_parser.go
=> Set User-Agent for GitLab API

gitlab/testdata/project_without_owner.json, gitlab/url_parser.go, gitlab/url_parser_test.go
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12b777d]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
goroutine 22 [running]:
testing.tRunner.func1(0xc00011c600)
/usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:830 +0x392
panic(0x130eac0, 0x15f9b40)
/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/sue445/gitpanda/gitlab.(*URLParser).fetchProjectURL(0xc000098460, 0x1381b04, 0x1f, 0x0, 0x0, 0x0)
/Users/sue445/dev/go/src/github.com/sue445/gitpanda/gitlab/url_parser.go:282 +0x23d
github.com/sue445/gitpanda/gitlab.(*URLParser).FetchURL(0xc00009 …
```
=> Fixed SEGV when non-user's project

README.md, gitlab/blob_fetcher.go, gitlab/color.go, gitlab/fetcher.go, gitlab/issue_fetcher.go, gitlab/job_fetcher.go, gitlab/merge_request_fetcher.go, gitlab/page.go, gitlab/pipeline_fetcher.go, gitlab/project_fetcher.go, gitlab/testdata/job.json, gitlab/testdata/pipeline.json, gitlab/url_parser.go, gitlab/url_parser_test.go, gitlab/user_fetcher.go, go.mod, go.sum, webhook/slack_webhook.go
=> Support Job URL and Pipeline URL

gitlab/blob_fetcher.go, gitlab/fetcher.go, gitlab/issue_fetcher.go, gitlab/job_fetcher.go, gitlab/merge_request_fetcher.go, gitlab/pipeline_fetcher.go, gitlab/project_fetcher.go, gitlab/project_snippet_fetcher.go, gitlab/testdata/project_with_subgroup.json, gitlab/url_parser_test.go
Support sub-group URL (e.g. https://gitlab.com/gitlab-org/memory-team/team-tasks/issues/9).
=> Support sub-group URL

examples/aws_sam_template.yaml
- Using CloudFormation Parameters
- Fix CodeUri, Handler
- Disable AWS X-Ray (look like not use in code)
only sam template refactoring.
run local testing `sam local invoke` is useful.
`sam package`  to create a deployment package.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-command-reference.html
=> Refactor AWS SAM Template

gitlab/blob_fetcher.go, gitlab/fetcher.go, gitlab/issue_fetcher.go, gitlab/job_fetcher.go, gitlab/merge_request_fetcher.go, gitlab/pipeline_fetcher.go, gitlab/project_snippet_fetcher.go, gitlab/url_parser_test.go
=> Support project routes including `/-/`

gitlab/blob_fetcher.go, gitlab/issue_fetcher.go, gitlab/job_fetcher.go, gitlab/merge_request_fetcher.go, gitlab/pipeline_fetcher.go, gitlab/project_fetcher.go, gitlab/project_snippet_fetcher.go, gitlab/snippet_fetcher.go, gitlab/url_parser.go, gitlab/user_or_group_fetcher.go, main_lambda_linux_amd64.go, webhook/slack_webhook.go
=> Wrap all error with `errors.WithStack`

.circleci/config.yml, go.mod
=> Upgrade to Go 1.16

go.mod, go.sum
Reverts sue445/gitpanda#621
this is test of dependabot-auto-merge
=> Revert "Bump github.com/aws/aws-sdk-go from 1.38.29 to 1.38.30"

.github/workflows/dependabot-auto-merge.yml
=> Revert app token

gitlab/job_fetcher.go, gitlab/job_fetcher_test.go, gitlab/testdata/job_trace.txt, gitlab/testdata/job_trace_plain.txt, gitlab/url_parser_test.go, go.mod, go.sum
e.g. https://gitlab.com/sue445/tanuki_reminder/-/jobs/1373568132#L110
Close #667
=> Supports to the line number anchor in the CI log

.github/workflows/docker-gcp.yml, README.md
=> Push docker image to GCP Artifact Registry

.github/cloud_run-service.yml, .github/workflows/docker-gcp.yml
=> Deploy to Cloud Run

.circleci/config.yml, Procfile, README.md, go.mod
=> Good bye Heroku

gitlab/project_fetcher.go, gitlab/url_parser_test.go
=> Fixed. 404 error for URLs containing anchors

README.md, gitlab/commit_fetcher.go, gitlab/testdata/commit.json, gitlab/url_parser.go, gitlab/url_parser_test.go
=> Support commit URL

.github/workflows/docker-gcp.yml, .github/workflows/docker-ghcr.yml, Dockerfile
=> Fixed Docker image not booting

.github/workflows/build.yml
ref. https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
=> Refactor: Enabled `merge-multiple` :golf:

.github/workflows/build.yml
Workaround for https://github.com/actions/download-artifact/issues/249
=> Run `actions/download-artifact@v4` with retry

gitlab/blob_fetcher.go, gitlab/commit_fetcher.go, gitlab/fetcher.go, gitlab/issue_fetcher.go, gitlab/job_fetcher.go, gitlab/merge_request_fetcher.go, gitlab/pipeline_fetcher.go, gitlab/project_fetcher.go, gitlab/project_snippet_fetcher.go, gitlab/snippet_fetcher.go, gitlab/url_parser.go, gitlab/user_or_group_fetcher.go, go.mod, go.sum
=> Migrate to gitlab.com/gitlab-org/api/client-go
